### ISSUE TITLE
延迟播放首次播放失败问题

### ISSUE THREAD

**Issue by HAAAAADION** [cirplan/audioPlayer#1]
@cirplan 请问你有尝试过ajax延迟播放吗?
类似:
```javascript
//模拟ajax
setTimeout(function(){
    audio.play();
}, 1001);
```
由于chrome机制问题,超过1000毫秒会自动阻止
请问有什么较优的解决方法?

**Comment by cirplan** [comment]
@HAAAAADION 抱歉这么久才回复。
刚尝试了下，在QQ和微信内，setTimout是可以播放的，chrome和UC浏览器下不行。
这是由浏览器机制决定的，后者是一定要接收到用户动作指令才会播放。
所以暂时没有很好的解决方法。
